export enum StudentStatus {
  QUICK_ADMISSION = 'QUICK_ADMISSION',
  SOFT_ADMISSION = 'SOFT_ADMISSION',
  ENROLLED = 'ENROLLED',
  EXPELLED = 'EXPELLED',
  GRADUATED = 'GRADUATED',
  LEFT = 'LEFT',
}
