export const CAMPUSES_MESSAGES = {
    CREATE_SUCCESS: 'Campus created successfully.',
    LIST_SUCCESS: 'Campuses fetched successfully.',
    DETAIL_SUCCESS: 'Campus details fetched successfully.',
    UPDATE_SUCCESS: 'Campus updated successfully.',
    DELETE_SUCCESS: 'Campus deleted successfully.',
    BULK_UPDATE_SUCCESS: 'Campuses updated successfully.',
    NOT_FOUND: 'Campus not found.',
    HAS_DEPENDENTS: 'Cannot delete campus with linked students or users.',
    CLASS_ADDED: 'Class added to campus successfully.',
    CLASS_UPDATED: 'Campus class updated successfully.',
    CLASS_REMOVED: 'Class removed from campus successfully.',
    SECTION_ADDED: 'Section added to campus/class successfully.',
    SECTION_UPDATED: 'Campus section updated successfully.',
    SECTION_REMOVED: 'Section removed from campus/class successfully.',
};
